// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatientService.Data;

#nullable disable

namespace PatientService.Migrations
{
    [DbContext(typeof(PatientDbContext))]
    partial class PatientDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PatientService.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1 Brookside St",
                            DateOfBirth = new DateOnly(1966, 12, 31),
                            FirstName = "Test",
                            Gender = "F",
                            LastName = "TestNone",
                            PhoneNumber = "100-222-3333"
                        },
                        new
                        {
                            Id = 2,
                            Address = "2 High St",
                            DateOfBirth = new DateOnly(1945, 6, 24),
                            FirstName = "Test",
                            Gender = "M",
                            LastName = "TestBorderline",
                            PhoneNumber = "200-333-4444"
                        },
                        new
                        {
                            Id = 3,
                            Address = "3 Club Road",
                            DateOfBirth = new DateOnly(2004, 6, 18),
                            FirstName = "Test",
                            Gender = "M",
                            LastName = "TestInDanger",
                            PhoneNumber = "300-444-5555"
                        },
                        new
                        {
                            Id = 4,
                            Address = "4 Valley Dr",
                            DateOfBirth = new DateOnly(2002, 6, 28),
                            FirstName = "Test",
                            Gender = "F",
                            LastName = "TestEarlyOnset",
                            PhoneNumber = "400-555-6666"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
